### ISSUE TITLE
No conection with gps neo m8n

### ISSUE THREAD

**Issue by damirm57** [prunkdump/arduino-variometer#16]
Hi, one more question. I have gps ublox neo m8n conected to vario, but i can not see any update only stay km/h without 0 or any number, Do I need some extra settings with ublox centar before conect to vario? On ublox centar gps funktion is OK.

**Comment by jpg63** [comment]
For the neo-8m the NMEA header is different a modification of the code of the library serialnmea.cpp #if defined (VARIOMETER_GPS_NEO6) const char rmcTag [] PROGMEM = {"GPRMC"}; const char ggaTag [] PROGMEM = {"GPGGA"}; #elif defined (VARIOMETER_GPS_NEO8) const char rmcTag [] PROGMEM = {"GNRMC"}; const char ggaTag [] PROGMEM = {"GNGGA"}; #else const char rmcTag [] PROGMEM = {"GPRMC"}; const char ggaTag [] PROGMEM = {"GPGGA"}; #endif must allow to operate the 2 GPS



________________________________
De : damirm57 <notifications@github.com>
Envoyé : lundi 29 janvier 2018 21:26
À : prunkdump/arduino-variometer
Cc : Subscribed
Objet : [prunkdump/arduino-variometer] No conection with gps neo m8n (#16)


Hi, one more question. I have gps ublox neo m8n conected to vario, but i can not see any update only stay km/h without 0 or any number, Do I need some extra settings with ublox centar before conect to vario? On ublox centar gps funktion is OK.

**Comment by damirm57** [comment]
Thank you for fast answer. I am try to integrate changes in code but obviousli in wrong way. Becose i how no exsperience in programing. When try to verify ino error message is:

C:\Program Files (x86)\Arduino\libraries\SerialNmea\SerialNmea.cpp:5:37: error: missing binary operator before token "const"
Please help.

**Comment by damirm57** [comment]
Thank you for fast answering!  I have no experience in programing and I am
try to implement changes in code without succes.

2018-01-29 22:41 GMT+01:00 jpg63 <notifications@github.com>:

**Comment by prunkdump** [comment]
Hi Damir.

Take the original code and just change the libraries/SerialNmea/SerialNmea.cpp from :
 
const char rmcTag[] PROGMEM = {"GPRMC"};
const char ggaTag[] PROGMEM = {"GPGGA"};

To 

const char rmcTag[] PROGMEM = {"GNRMC"};
const char ggaTag[] PROGMEM = {"GNGGA"};

And it's ok.

Regards,

Baptiste.

**Comment by damirm57** [comment]
Awesome,  gps fix is done. Thanks Baptiste, fantastic project. I am
begginer in paragliding, thank you, thank you!!!!
Is it posibile  to conect aditional board mpu9250 without ms5611(this is
already conected) I have one more rest  from Ed tracker project.

2018-01-30 19:24 GMT+01:00 prunkdump <notifications@github.com>:

**Comment by jpg63** [comment]
I added the management of the neo-8m GPS in the branch jpg63-version on the github

the choice between neo-6 and neo-8 is done in the file variosettings.h

jean-philippe

________________________________
De : damirm57 <notifications@github.com>
Envoyé : mardi 30 janvier 2018 20:51
À : prunkdump/arduino-variometer
Cc : jpg63; Comment
Objet : Re: [prunkdump/arduino-variometer] No conection with gps neo m8n (#16)

Awesome, gps fix is done. Thanks Baptiste, fantastic project. I am
begginer in paragliding, thank you, thank you!!!!
Is it posibile to conect aditional board mpu9250 without ms5611(this is
already conected) I have one more rest from Ed tracker project.

2018-01-30 19:24 GMT+01:00 prunkdump <notifications@github.com>:

**Comment by prunkdump** [comment]
Good news !

Yes Damir you can connect your mpu9250 board on the same pins (A4 and A5).

If it don't works, add : 
-> one 4,7k resistor between A4 and 3.3V
-> one 4,7k resistor between A5 and 3.3V

Regards,

Baptiste.

**Comment by damirm57** [comment]
Thank you again!

2018-01-31 7:13 GMT+01:00 prunkdump <notifications@github.com>:

**Comment by prunkdump** [comment]
It's now possible to correct this in VarioSettings.h

Thanks for the report.
