### ISSUE TITLE
Using a NEO6MV2 (XM37-1612) , old GPS

### ISSUE THREAD

**Issue by olitask** [prunkdump/arduino-variometer#25]
Hello 
I've been using an old NEO6MV2 , XM37-1612 GPS . I got totally wrong information for time & speed . To correct this, You' have to edit NmeaParse.h  and change to 
```
#define NMEA_PARSER_RMC_SPEED_PRECISION 100 // initialement 1000.0
#define NMEA_PARSER_GGA_TIME_PRECISION 1000   //initialement  100
#define NMEA_PARSER_GGA_ALTITUDE_PRECISION 100.0  //initialement  10.0
```
Thanks to Baptiste .

**Comment by prunkdump** [comment]
These parameters have now moved to VarioSettings.h.

Thanks for the report.
