### ISSUE TITLE
Issue after HW upgrade to NEO6MV2 and 10DOF (5611/9250)

### ISSUE THREAD

**Issue by LL03** [prunkdump/arduino-variometer#26]
Hello,
I replaced my old GPS module by the blue NEO6MV2 and the 10DOF sensor whith combined MS5611 and MPU9250. Before it was the red NEO6M and the MS5611 and MPU9250 separate. 
I am using the jpg63 software. With the new software the display starts blinking after around 30s and is frozen and no sound. Then it restarts and it could also happen that the display is mixed up and there is a continous sound before it restarts again.

The display is OK
![vario1](https://user-images.githubusercontent.com/45431706/49166806-65688e00-f334-11e8-9bea-0fbbd6329094.JPG)
The display is mixed up and the attitude changes to baro value. After the automatic restart it is like the first picture again.
![vario2](https://user-images.githubusercontent.com/45431706/49166896-8e891e80-f334-11e8-9889-4e8c28708e01.JPG)

I read the issue "Using a NEO6MV2 (XM37-1612) , old GPS" and changed the NMEA_Parser settings and the restart problem is solved but the shown valeus for the time and attitude are wrong.

//#define NMEA_PARSER_RMC_SPEED_PRECISION 1000.0
//#define NMEA_PARSER_GGA_TIME_PRECISION 100
//#define NMEA_PARSER_GGA_ALTITUDE_PRECISION 10.0
#define NMEA_PARSER_RMC_SPEED_PRECISION 100 // initialement 1000.0
#define NMEA_PARSER_GGA_TIME_PRECISION 1000   //initialement  100
#define NMEA_PARSER_GGA_ALTITUDE_PRECISION 100.0  //initialement  10.0

What is the meaning of the parameters and what are valid values. Which can I use that the values are correct but my restart problem is further solved?

Best regards
LL03

**Comment by LL03** [comment]
So I did another test and removed the TX line from the GPS. It remains the same issue, that I now think it is the 10DOF sensor whith combined MS5611 and MPU9250 (purple version). Could it happen if the 10DOF is not delivering correct or constantly values? I build two devices and the behaviour is the same.

**Comment by prunkdump** [comment]
Hi LL03 !

The problem you describe seems to be a powering problem.

When you power-on your variometer something need to much current that you power circuit can't feed. So the voltage decrease greatly and the ms5611 ( very sensitive to power ) give bad values. This is because your screen display too big numbers.

Sometimes the voltage decrease so much that is goes under the Arduino brown out detection. So a reset is launched and the Arduino reboot.

How do you power your components ? Have you changed some voltage regulators ?

The "blue" neo-6M does not not need code modification. You can keep the original code. But it need power as it is a little hungry ;)

Regards,

Baptiste.

**Comment by LL03** [comment]
Hi Baptiste,
I will measure the overall current. I have a Lipo as power supply all componeents are directly connected to the Lipo except the Display and MicroSD card reader, but without SD card in it. They are connected to VCC (3.3V). I will desolder the reader.
Thank you I will inform you.
Regards
LL03

**Comment by prunkdump** [comment]
I think the SD card reader is not the problem. Don't take the risk to damage it while removing it.

-> Measure the input voltage of your ms5611 (between VCC and GND). It must be above 3.5v.
-> Try disabling the accelerometer in VarioSettings.h
//HAVE_ACCELEROMETER
To check if the problem come from the ms5611 or the mpu9250.
-> Try to make again all the soldering by adding a little amount of solder.
-> Clean the flux. 

Your LiPo battery is not too small ? You need at least a 400mAh battery.

Regards,

Baptiste.

**Comment by LL03** [comment]
Hi Baptiste,
I measured the current and it is around 100mA and the card reader alone without SD Card only some mA. But without the card reader the vario works. I assume that the connected signal pins are the root cause.
Do you recommend a specific micro SD card reader and can I use a 3.3V type?
I think the issue can be closed.
Regards
LL03

**Comment by LL03** [comment]
Hi Baptiste,
the Lipo has 1000mA and the voltage at the supply pins is 3,8V. I desoldered the reader an now it works. Then I used a different microSD reader type, also with 3,3V and it works too without reset. Now it can also write IGC files. So I will replace the modules. For the support two pictures. The 1st which works fine and the 2nd which is not usable.
![microsd-ok](https://user-images.githubusercontent.com/45431706/49182704-43cecd00-f35b-11e8-9a4a-118bb164e256.JPG)
![microsd-bad](https://user-images.githubusercontent.com/45431706/49182708-46c9bd80-f35b-11e8-8971-caa6473c043c.JPG)
Regards
LL03

**Comment by prunkdump** [comment]
Thanks for your feedback !

But I think your previous SD card module have a problem. Some short circuit maybe.

i use the same module than you : 

https://prunkdump.github.io/GNUVario/tutorials/boards.html

Regards,

Baptiste.

**Comment by prunkdump** [comment]
I close the issue.

**Comment by LL03** [comment]
Many thanks for the support:-)
Can I ask a question or should I open a new topic?
With the other module (which you use) I have the reset problem sometimes too without SD  Card in the slot. 
When I solder a SD module and configure "Have SD card", is it mandatory to plug in a SD card?
If this configuration causes problems, can I solve it by a configuration change: Deactivate "Have SD card"?
If that is the case can the programm be more tolerant if an SD card is not available?
Best regards
LL03

**Comment by prunkdump** [comment]
Hi LL03 !

You can contact me directly if you want. You have my email on my profile.

I think that the problem come from your soldering. Disabling the SD card in the code will not help.

Check if  there is not too much solder on the SD card pins that can make short circuits.

Don't hesitate to contact me.

Baptiste.

**Comment by prunkdump** [comment]
Someone give the solution to me !

Simply put a wire between the IMU AD0 pin and ground (GND) !

I think this will solve your issue !

Regards,

Baptiste
