### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [prunkdump/arduino-variometer#27]
I was linked to this page from https://prunkdump.github.io/GNUVario/.

There is no license for this project. The default is copyright.

You should license this project under the AGPL3 or GPL3 license. If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by prunkdump** [comment]
Hi !

Excuse me for the delay, I'm working hard on the next release where the whole code is redesigned.

Don't worry, the code will be updated soon to fit the GNU GPLv3 licence.

If you need some part of the code for another project don't hesitate. I will give copyleft on the next release.

Regards,

Baptiste.

**Comment by prunkdump** [comment]
Hi Michael !

I have released the whole project under GPLv3 now.

Thanks for the help doing this !

**Comment by TechnologyClassroom** [comment]
Thank you!
