### ISSUE TITLE
Cannot compile SetVarioParameters

### ISSUE THREAD

**Issue by Hasi123** [prunkdump/arduino-variometer#29]
I tried to compile SetVarioParameters for the 328P, but it gives me this error message:

> Arduino: 1.8.7 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (3.3V, 8 MHz)"
> 
> Build options changed, rebuilding all
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `decodeCompressedFirmware()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `loadCompressedFirmware()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `disableDMP()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `enableDMP()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastFIFOReset()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `readMagSensAdj()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `saveInt32(long, unsigned char*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `computeGyroBias(long, unsigned char*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetGyroBias(unsigned char const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUReadGyroBias(unsigned char*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetGyroBias(int const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetGyroBiasQ16(long const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetAccelBias(unsigned char const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUReadAccelBias(unsigned char*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetAccelBias(int const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetAccelBiasQ15(long const*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUInit(bool)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUStart()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUSetTapCallback(void (*)(unsigned char, unsigned char))'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `tapCallBack'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUReadFIFO(int*, int*, long*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUMagReady()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUReadRawMag(int*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUGetMagSensAdj()'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> libraries\LightInvensenseOld\LightInvensenseOld.cpp.o (symbol from plugin): In function `decodeCompressedFirmware()':
> 
> (.text+0x0): multiple definition of `fastMPUReadMag(int*)'
> 
> libraries\LightInvensense\LightInvensense.cpp.o (symbol from plugin):(.text+0x0): first defined here
> 
> collect2.exe: error: ld returned 1 exit status
> 
> exit status 1
> Error compiling for board Arduino Pro or Pro Mini.
> 
> This report would have more information with
> "Show verbose output during compilation"
> option enabled in File -> Preferences.

**Comment by prunkdump** [comment]
Thanks for the bug report !

The problem is solved now on the last version.

Be careful, on the last version, some parameter names have changed. When you update your VarioSettings.h just copy the values and not the whole lines.

Regards,

Baptiste.
