### ISSUE TITLE
Which case are you using in your tutorial?

### ISSUE THREAD

**Issue by lshachar** [prunkdump/arduino-variometer#36]
Hi @prunkdump ! 
Just starting to make another gnuVario, this time I'd like to follow your hardware tutorial and build a complete one (my current does not have a battery or a screen)

I'm wondering what case are you using, do you have a part number, or maybe a 3d model that I could print out?

thank you!  :)

P/S, I'm currently hunting down for the exact components that you're using on your PCB, for obvious reasons - I want everything to work out with the same PCB. It would be great if you could mention the module references in your tutorial.,
I,e, if it helps someone, [micro sd module](https://www.aliexpress.com/item/32867572635.html?spm=a2g0o.cart.0.0.55903c00iYpLCK&mp=1)
Arduino pro mini 3.3V
[micro usb lithium battery charger module 03962A](https://www.aliexpress.com/item/32986135934.html?spm=a2g0o.cart.0.0.55903c00iYpLCK&mp=1)
[spdt switch + 90 deg angle](https://www.aliexpress.com/item/32864652652.html?spm=a2g0o.cart.0.0.55903c00iYpLCK&mp=1)
[MPU9250/MS5611 CJMCU-117](https://www.aliexpress.com/item/32846185344.html?spm=a2g0o.productlist.0.0.48267be0k81re2&algo_pvid=a4827eb3-2b54-4201-85a7-7f4b945d4b4c&algo_expid=a4827eb3-2b54-4201-85a7-7f4b945d4b4c-4&btsid=83f6d057-4e4d-40ed-8216-59362875a1af&ws_ab_test=searchweb0_0,searchweb201602_1,searchweb201603_53)

**Comment by prunkdump** [comment]
Hi Ishachar.

I can't put commercial informations here.

Please contact me with the email address given in my profile. I will sent to you back a complete BOM with all the components needed and where to find them.

Regards,

Baptiste.

**Comment by lshachar** [comment]
Hi, I did! (14th January)
Just sent it again.
Thanks for your help :)
