### ISSUE TITLE
Suggestion: extra Define to set MPU I2C address to 0x69 

### ISSUE THREAD

**Issue by sbishop61** [prunkdump/arduino-variometer#9]
Baptiste,
 in order to try and get a prototype into a box to calibrate I have used a cjmcu-117 as I think you have.
Unfortunately there seems to be some short on the board as the I2c address keeps changing from 0x68 to 0x69 and back again. The solution is to set ADO to 1 which holds the address at 0x69.

I can get it to work by editing inv_mpu.cpp where #define GYRO_HW_ADDR (0x68) is set both for MPU6050 and separately for MPU6500.

A suggestion would be to have a define in VarioSettings.h rather than in the C++ file.

regards
Stephen

**Comment by prunkdump** [comment]
You can now set the MPU address in VarioSetting.h

Thanks for the report.

Baptiste.
